---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/EHRA/EHRA.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/2191/articles/278438/master/file/figures/EHRA/EHRA.png"
    folder_url: "/users/2191/articles/278438/master/folder/figures/EHRA"
